receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    limit_mib: 512
    check_interval: 1s

exporters:
  # Prometheus export for Grafana
  prometheus:
    endpoint: "0.0.0.0:8090"
    const_labels:
      cluster: vntp-demo
  
  # SigNoz export via OTLP
  otlp/signoz:
    endpoint: otel-collector-signoz:4317
    tls:
      insecure: true
    headers:
      signoz-access-token: ""
  
  # Debug logging
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/signoz, debug]
    
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus, otlp/signoz, debug]
    
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/signoz, debug]