global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'signoz-otel-collector'
    static_configs:
      - targets: ['localhost:8889']
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres-imisanzu'
    static_configs:
      - targets: ['postgres-exporter-imisanzu:9187']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'postgres-oracle'
    static_configs:
      - targets: ['postgres-exporter-oracle:9187']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    metrics_path: /metrics
    scrape_interval: 30s