global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector-signoz:8889']
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: 'signoz-otel-collector'
    static_configs:
      - targets: ['otel-collector-signoz:8888']
    metrics_path: /metrics
    scrape_interval: 15s